### ISSUE TITLE
Good and bad posts analysis

### ISSUE THREAD

**Issue by andreybleme** [mateusmcg/bigdata-search#1]
Would be nice to have a accurate analysis about good :blush: and bad :weary: posts! 

Take a look at this sentiment analysis module for node.js (https://github.com/thisandagain/sentiment), it might be helpfull.

:+1:

**Comment by mateusmcg** [comment]
This feature is indeed in our queue to do.

We'll take a look at this module for sure! Any tips feel free to tell us.

Thanks a lot :)
